import=[
    "~/.config/alacritty/alacritty-kb/key-bindings.toml",
    "~/.config/alacritty/alacritty-themes/zenburn.toml"
]
live_config_reload=true
[env]
TERM = "xterm-256color"
[window]
dimensions={columns=150, lines=25}
padding={x=2,y=2}
title="Alacritty"
dynamic_title=false
opacity=0.8
blur=false
[font]
size=10 
[font.bold]
family="D2CodingLigature Nerd Font"
style = "Bold"
[font.bold_italic]
family = "D2CodingLigature Nerd Font"
style = "Bold Italic"
[font.italic]
family = "D2CodingLigature Nerd Font"
style = "Italic"
[font.normal]
family = "D2CodingLigature Nerd Font"
style = "Regular"
[selection]
save_to_clipboard = true
[cursor]
blink_interval=250
thickness=0.5
[cursor.style]
shape="Beam"
blinking="Always"
[mouse]
hide_when_typing = false
