import = ["/home/urban/.config/alacritty/alacritty-kb/key-bindings.toml"]
#print_events = true
#theme = "Tokyonight_Night"

[colors]
#author = "Folke"
#name = "TokyoNight Night"

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x15161E"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[cursor]
blink_interval=250

[cursor.style]
shape="Beam"
blinking="Always"

[env]
TERM = "xterm-256color"

[font]
size = 8 

[font.bold]
family = "SauceCodePro NF"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro NF"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro NF"
style = "Italic"

[font.normal]
family = "SauceCodePro NF"
style = "Regular"

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true

[window]
dynamic_title = false
title = "Alacritty"
