[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Super"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Super"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Super"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "F12"
